task_management/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from core.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
    path('users/', include('users.urls')),
    path('',home, name='home')
] + debug_toolbar_urls()

tasks/urls.py
from django.urls import path
from tasks.views import manager, user, taskForm, update_task, delete_task

urlpatterns = [
    path('manager', manager, name='manager'),
    path('user', user, name='user'),
    path('taskform',taskForm, name='taskForm'),
    path('update-task/<int:id>/',update_task, name='update-task'),
    path('delete-task/<int:id>/', delete_task, name='delete-task')
]

users/urls.py
from django.urls import path
from users.views import sign_up, signIn, logOut, user_activate


urlpatterns = [
    path('sign-up/',sign_up, name='sign-up'),
    path('signin',signIn, name='signin'),
    path('logOut',logOut, name='logout'),
    path('activate/<int:user_id>/<str:token>/', user_activate)
]

core/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models
from django.db.models.signals import pre_save, m2m_changed
from django.dispatch import receiver
from django.core.mail import send_mail

# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField()

    def __str__(self):
        return self.name

class Employee(models.Model):
    name = models.CharField(max_length=250)
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.name

class Task(models.Model):
    STATUS_CHOICE = (
        ('PENDING','Pending'),
        ('IN_PROGRESS','In_progress'),
        ('COMPLETED','Completed')
    )
    status = models.CharField(max_length=20, choices=STATUS_CHOICE, default='PENDING')
    project = models.ForeignKey(Project, on_delete=models.CASCADE, default=1, related_name='project')
    employee = models.ManyToManyField(Employee, related_name='employee')
    title = models.CharField(max_length=250)
    description = models.TextField()
    due_date = models.DateField()
    is_completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    

class TaskDetail(models.Model):
    HIGH = 'H'
    MIDIUM = 'M'
    LOW = 'L'
    PRIORITY_CHOICES = (
        (HIGH, 'Hight'),
        (MIDIUM, 'Medium'),
        (LOW, 'Low')
    )
    task = models.OneToOneField(Task, on_delete=models.CASCADE, related_name='details')
    
    priority = models.CharField(max_length=1, choices=PRIORITY_CHOICES, default=LOW)

    def __str__(self):
        return self.priority

@receiver(pre_save, sender=Task)
def task_notification(sender, instance, **kwargs):
    instance.is_completed = True

@receiver(m2m_changed, sender=Task.employee.through)
def task_email_notification(sender, instance, action, **kwargs):
    if action == 'post_add':
        send_emails = [emp.email for emp in instance.employee.all()]
        send_mail(
            "New Task Assigned",
            f"You have been assigned to the Task : {instance.title}",
            "zahidallsquare@gmail.com",
            send_emails
        )

tasks/forms.py
from tasks.models import Task, TaskDetail
from django import forms

class taskFormModel(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'

class taskDetailsModel(forms.ModelForm):
    class Meta:
        model = TaskDetail
        fields = ['priority']

users/forms.py
from django import forms
import re
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
class CustomRegiForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput)
    confirm_pass = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','password1','confirm_pass']

    def clean_email(self):
        email = self.cleaned_data['email']
        email_exist = User.objects.filter(email=email).exists()

        if email_exist:
            raise forms.ValidationError("Email already exists try another email")
        return email
    
    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if len(password1) < 4:
            raise forms.ValidationError("Password lenth should be more than 3 letters")
        return password1
    
    def clean(self):
        cleaned_data = super().clean()
        pass1 = cleaned_data.get('password1')
        pass2 = cleaned_data.get('confirm_pass')
        print(pass2,pass1)
        if pass1 and pass2 and pass1 != pass2:
            raise forms.ValidationError("Password does not match")
        return cleaned_data

        
        
        

core/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,'home.html')

tasks/views.py
from django.shortcuts import redirect, render
from tasks.forms import taskFormModel, taskDetailsModel
from django.contrib import messages
from tasks.models import Task
# Create your views here.
def manager(request):
    task = Task.objects.all()
    context = {
        'tasks' : task
    }
    return render(request, 'manager.html', context)

def user(request):
    return render(request, 'user.html')

def taskForm(request):
    form = taskFormModel()
    form2 = taskDetailsModel()
    if request.method == 'POST':
        form = taskFormModel(request.POST)
        form2 = taskDetailsModel(request.POST)
        if form.is_valid() and form2.is_valid():
            task = form.save()
            task2 = form2.save(commit=False)
            task2.task = task
            task2.save()
            messages.success(request, 'Succesfull')
            return redirect('taskForm')
            
    return render(request, 'form/task.html', {"form":form, "form2":form2})


def update_task(request,id):
    task = Task.objects.get(id=id)
    form = taskFormModel(instance=task)
    if task.details:
        form2 = taskDetailsModel(instance=task.details)
    if request.method == 'POST':
        form = taskFormModel(request.POST, instance=task)
        form2 = taskDetailsModel(request.POST, instance=task.details)
        if form.is_valid() and form2.is_valid():
            task = form.save()
            task2 = form2.save(commit=False)
            task2.task = task
            task2.save()
            messages.success(request, 'Succesfull')
            return redirect('update-task',id)
            
    return render(request, 'form/task.html', {"form":form, "form2":form2})

def delete_task(request, id):
    task = Task.objects.get(id=id)
    if request.method == 'POST':
        task.delete()
        messages.success(request,'Delete successful')
        return redirect('manager')

users/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from users.forms import CustomRegiForm
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.tokens import default_token_generator
# Create your views here.
def sign_up(request):
    form = CustomRegiForm()
    if request.method == 'POST':
        form = CustomRegiForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data.get('password1'))
            user.is_active = False
            user.save()
            messages.success(request,"success")
    
    return render(request,'signup.html',{'form':form})

def signIn(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('home')
            
    return render(request,'signin.html',{'form':form})

def logOut(request):
    if request.method == 'POST':
        logout(request)
        return redirect('signin')


def user_activate(request,user_id,token):
    try:
        user = User.objects.get(id = user_id)
         
        if default_token_generator.check_token(user,token):

            user.is_active = True
            user.save()
            return redirect('signin')
        else:
            return HttpResponse(request,"User Id Invalid")
    except User.DoesNotExist:
        return HttpResponse(request,"User Not found")

core/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
     <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    
</head>
<body class="text-xl">
    {% if request.user.is_authenticated %}
       <header class="py-3 bg-red-400">
        <div class="nav-bar flex justify-around">
            <div class="logo">Event</div>
            <div class="menu">
                <ul class="flex justify-between gap-4 text-white">
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><a href="#">Dashboard</a></li>
                    <li><form action="{% url 'signin' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Log Out</button>
                    </form></li>
                </ul>
            </div>
        </div>
    </header>
    
   
{%else%}
 <header class="py-3 bg-red-400">
        <div class="nav-bar flex justify-around">
            <div class="logo">Event</div>
            <div class="menu">
                <ul class="flex justify-between gap-4 text-white">
                    <li><a href="#">Home</a></li>
                    <li><a href="{% url 'signin' %}">Log In</a></li>
                    
                </ul>
            </div>
        </div>
    </header>
    
    {% endif %}
   <h1 class="text-center text-2xl mt-4"> welcome  to home</h1>
   
</body>
</html>

tasks/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <title>user area</title>
    <link rel="stylesheet" href="htps://cdn.tailwindcss.com">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">
</head>
<body class="p-6 bg-gray-50" style="font-family: inter;">
  <div class="container max-w-[1300px] mx-auto">
      <header class="flex justify-between items-center mb-4">
        <h1 class="text-xl">Dashboard</h1>
        <div class="icon-area flex justify-between items-center gap-4">
            <button class="hover:bg-red-500 p-2 rounded-full text-xl hover:cursor-pointer">
                <svg class="w-6 h-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 0 0 5.454-1.31A8.967 8.967 0 0 1 18 9.75V9A6 6 0 0 0 6 9v.75a8.967 8.967 0 0 1-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 0 1-5.714 0m5.714 0a3 3 0 1 1-5.714 0" />
            </svg>
            </button>

            <button class="hover:pointer-events-auto w-10 h-10 rounded-full hover:bg-red-500 bg-red-500 font-semibold text-white">
                B
            </button>
        </div>
    </header>

    <!-- next area -->

      
     <div class="grid-area grid md:grid-cols-4 grid-cols-1 gap-6">
        <!-- Total Area Start-->
        <div class="bg-white-500  rounded-md shadow-sm p-4">
            <h2 class="text-gray-500 mb-2">TOTAL TASK</h2>
            <div class="flex justify-between items-start">
                <div class="">
                    <p class="text-lg font-semibold">3</p>
                    <p class="text-gray-500">11 last month</p>
                </div>
                <div class="icon">
                    <button class="rounded-full p-3 bg-blue-100">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2"  stroke="currentColor" class="h-6 w-6 text-blue-600">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M15.666 3.888A2.25 2.25 0 0 0 13.5 2.25h-3c-1.03 0-1.9.693-2.166 1.638m7.332 0c.055.194.084.4.084.612v0a.75.75 0 0 1-.75.75H9a.75.75 0 0 1-.75-.75v0c0-.212.03-.418.084-.612m7.332 0c.646.049 1.288.11 1.927.184 1.1.128 1.907 1.077 1.907 2.185V19.5a2.25 2.25 0 0 1-2.25 2.25H6.75A2.25 2.25 0 0 1 4.5 19.5V6.257c0-1.108.806-2.057 1.907-2.185a48.208 48.208 0 0 1 1.927-.184" />
                        </svg>
                    </button>
                </div>
            </div>
        </div>
        <!-- Toatal area end -->
        <!-- Total Area Start-->
        <div class="bg-white-500 rounded-md shadow-sm p-4">
            <h2 class="text-gray-500 mb-2">TOTAL TASK</h2>
            <div class="flex justify-between items-start">
                <div class="">
                    <p class="text-lg font-semibold">3</p>
                    <p class="text-gray-500">11 last month</p>
                </div>
                <div class="icon">
                    <button class="rounded-full p-3 bg-yellow-100">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="h-6 w-6 text-yellow-600">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
                        </svg>

                        </svg>
                    </button>
                </div>
            </div>
        </div>
        <!-- Toatal area end -->
        <!-- Total Area Start-->
        <div class="bg-white-500 rounded-md shadow-sm p-4">
            <h2 class="text-gray-500 mb-2">TOTAL TASK</h2>
            <div class="flex justify-between items-start">
                <div class="">
                    <p class="text-lg font-semibold">3</p>
                    <p class="text-gray-500">11 last month</p>
                </div>
                <div class="icon">
                    <button class="rounded-full p-3 bg-green-100">
                       <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="h-6 w-6 text-green-600">
  <path stroke-linecap="round" stroke-linejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
</svg>

                    </button>
                </div>
            </div>
        </div>
        <!-- Toatal area end -->
        <!-- Total Area Start-->
        <div class="bg-white-500 rounded-md shadow-sm p-4">
            <h2 class="text-gray-500 mb-2">TOTAL TASK</h2>
            <div class="flex justify-between items-start">
                <div class="">
                    <p class="text-lg font-semibold">3</p>
                    <p class="text-gray-500">11 last month</p>
                </div>
                <div class="icon">
                    <button class="rounded-full p-3 bg-purple-100">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2"  stroke="currentColor" class="h-6 w-6 text-purple-600">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M15.666 3.888A2.25 2.25 0 0 0 13.5 2.25h-3c-1.03 0-1.9.693-2.166 1.638m7.332 0c.055.194.084.4.084.612v0a.75.75 0 0 1-.75.75H9a.75.75 0 0 1-.75-.75v0c0-.212.03-.418.084-.612m7.332 0c.646.049 1.288.11 1.927.184 1.1.128 1.907 1.077 1.907 2.185V19.5a2.25 2.25 0 0 1-2.25 2.25H6.75A2.25 2.25 0 0 1 4.5 19.5V6.257c0-1.108.806-2.057 1.907-2.185a48.208 48.208 0 0 1 1.927-.184" />
                        </svg>
                    </button>
                </div>
            </div>
        </div>
        <!-- Toatal area end -->
     </div>
  </div>

    {% block tasks %}
      
    {% endblock tasks %}
</body>
</html>

tasks/templates/form/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">submit</button>
    </form>
</body>
</html>

tasks/templates/form/task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Task form</title>
</head>
<body>
        <div class="form">
                {% if messages %}
                        {% for message in messages  %}
                                <p class="" style="color: green;">{{message}}</p>
                        {% endfor %}
                {% endif %}
                <form action="" method="post">
                        {% csrf_token %}
                        {{form.as_p}}
                        {{form2.as_p}}
                        <button type="submit">Submit</button>
                </form>

                
            
        </div>
</body>
</html>

tasks/templates/manager.html
    {% include "base.html" %}
    <!-- Grid Area -->
     {% block tasks %}
       
   
  <!-- Next Area -->
  <div class="data-area container max-w-[1300px] mx-auto divide-y divide-gray-200 p-4 bg-white-500 shadow-md rounded-md
  mt-4">
        <div class="row grid md:grid-cols-4 grid-cols-1 py-4">
            <div class="text-md text-gray-500">Task Title</div>
            <div class="text-md text-gray-500">Priority</div>
            <div class="text-md text-gray-500">Team</div>
            <div class="text-md text-gray-500">Credit At</div>
        </div>
{% for task in tasks  %}
  
        <div class="row grid md:grid-cols-4 grid-cols-1 py-4">
            <div class="text-xl text-gray-500 flex items-center gap-2">
                <div class="w-2 h-2 rounded-full bg-green-500"></div>
                <div class="text-sm">{{task.title}}<span><a style="color: rgb(247, 247, 247); border-radius: 4px; background: purple;
                padding: 2px 5px; margin-left:10px" href="{% url 'update-task' task.id %}"> Edit</a></span>
                <form action="{% url 'delete-task' task.id %}" method="post">
                    {% csrf_token %}
                    <button style="background-color: red;" type="submit">Delete</button>
                </form>    
          
            </div>
                
            </div>
            <div class="flex items-center">
                <span class="bg-blue-100 text-sm px-4 py-1 font-semibold rounded-full text-blue-500">{{task.details.get_priority_display}}</span>
            </div>
            <div class="flex justify-start items-center -space-x-2">
                {% for emp in task.employee.all  %}
                    <div class="bg-blue-600 text-sm w-8 h-8 font-semibold rounded-full text-white 
                border border-white-500 flex justify-center items-center">{{emp.name}}</div>
                {% endfor %}
                
               
            </div>
            <div class="text-sm text-gray-500">{{task.created_at|timesince}}</div>
        </div>

{% endfor %}

  </div>
{% endblock tasks %}
  

tasks/templates/user.html
{% include "base.html" %}
{% block tasks %}

  <!-- Next Area -->
  <div class="area-divide grid grid-cols-2 container max-w-[1300px] mx-auto gap-6">
        <!-- Left area -->
        <div class="left-area p-4 bg-white-500 shadow-md rounded-md
  mt-4">
            <h1 class="text-xl py-2 text-bold">Today's Tasks</h1>
            <div class="t1 flex items-center justify-between p-2">
                <div class="dot-text flex items-center gap-2">
                    <div class="h-2 w-2 rounded-full bg-green-500"></div>
                    <p class="text-gray-500 text-sm">Complete project proposal</p>
                </div>
                <div class="text-gray-500 text-md">
                    Right
                </div>
            </div>
            <div class="t1 flex items-center justify-between p-2">
                <div class="dot-text flex items-center gap-2">
                    <div class="h-2 w-2 rounded-full bg-green-500"></div>
                    <p class="text-gray-500 text-sm">Complete project proposal</p>
                </div>
                <div class="text-gray-500 text-md">
                    Right
                </div>
            </div>
            <div class="t1 flex items-center justify-between p-2">
                <div class="dot-text flex items-center gap-2">
                    <div class="h-2 w-2 rounded-full bg-green-500"></div>
                    <p class="text-gray-500 text-sm">Complete project proposal</p>
                </div>
                <div class="text-gray-500 text-md">
                    Right
                </div>
            </div>
         
        </div>

        <!-- Right area -->
        <div class="right-area">
            <div class="data-area container max-w-[1300px] mx-auto p-4 bg-white-500 shadow-md rounded-md
  mt-4">
            <h1 class="text-xl py-2 text-bold">All Tasks</h1>
        <div class="row grid md:grid-cols-4 grid-cols-1 py-2">
            <div class="text-md text-gray-500">Task Title</div>
            <div class="text-md text-gray-500">Priority</div>
            <div class="text-md text-gray-500">Team</div>
            <div class="text-md text-gray-500">Credit At</div>
        </div>

        <div class="row grid md:grid-cols-4 grid-cols-1 py-2">
            <div class="text-xl text-gray-500 flex items-center gap-2">
                <div class="w-2 h-2 rounded-full bg-green-500"></div>
                <div class="text-sm">Test Low Task</div>
            </div>
            <div class="flex items-center">
                <span class="bg-blue-100 text-sm px-4 py-1 font-semibold rounded-full text-blue-500">Low</span>
            </div>
            <div class="flex justify-start items-center -space-x-2">
                <div class="bg-blue-600 text-sm w-8 h-8 font-semibold rounded-full text-white border border-white-500 flex justify-center items-center">CA</div>
                <div class="bg-blue-600 text-sm w-8 h-8 font-semibold rounded-full text-white border border-white-500 flex justify-center items-center">JS</div>
                <div class="bg-blue-600 text-sm w-8 h-8 font-semibold rounded-full text-white border border-white-500 flex justify-center items-center">B</div>
            </div>
            <div class="text-sm text-gray-500">9 months ago</div>
        </div>

        <div class="row grid md:grid-cols-4 grid-cols-1 py-2">
            <div class="text-xl text-gray-500 flex items-center gap-2">
                <div class="w-2 h-2 rounded-full bg-green-500"></div>
                <div class="text-sm">Test Low Task</div>
            </div>
            <div class="flex items-center">
                <span class="bg-blue-100 text-sm px-4 py-1 font-semibold rounded-full text-blue-500">Low</span>
            </div>
            <div class="flex justify-start items-center -space-x-2">
                <div class="bg-blue-600 text-sm w-8 h-8 font-semibold rounded-full text-white border border-white-500 flex justify-center items-center">CA</div>
                <div class="bg-blue-600 text-sm w-8 h-8 font-semibold rounded-full text-white border border-white-500 flex justify-center items-center">JS</div>
                <div class="bg-blue-600 text-sm w-8 h-8 font-semibold rounded-full text-white border border-white-500 flex justify-center items-center">B</div>
            </div>
            <div class="text-sm text-gray-500">9 months ago</div>
        </div>

        <div class="row grid md:grid-cols-4 grid-cols-1 py-2">
            <div class="text-xl text-gray-500 flex items-center gap-2">
                <div class="w-2 h-2 rounded-full bg-green-500"></div>
                <div class="text-sm">Test Low Task</div>
            </div>
            <div class="flex items-center">
                <span class="bg-blue-100 text-sm px-4 py-1 font-semibold rounded-full text-blue-500">Low</span>
            </div>
            <div class="flex justify-start items-center -space-x-2">
                <div class="bg-blue-600 text-sm w-8 h-8 font-semibold rounded-full text-white border border-white-500 flex justify-center items-center">CA</div>
                <div class="bg-blue-600 text-sm w-8 h-8 font-semibold rounded-full text-white border border-white-500 flex justify-center items-center">JS</div>
                <div class="bg-blue-600 text-sm w-8 h-8 font-semibold rounded-full text-white border border-white-500 flex justify-center items-center">B</div>
            </div>
            <div class="text-sm text-gray-500">9 months ago</div>
        </div>

        <div class="row grid md:grid-cols-4 grid-cols-1 py-2">
            <div class="text-xl text-gray-500 flex items-center gap-2">
                <div class="w-2 h-2 rounded-full bg-green-500"></div>
                <div class="text-sm">Test Low Task</div>
            </div>
            <div class="flex items-center">
                <span class="bg-blue-100 text-sm px-4 py-1 font-semibold rounded-full text-blue-500">Low</span>
            </div>
            <div class="flex justify-start items-center -space-x-2">
                <div class="bg-blue-600 text-sm w-8 h-8 font-semibold rounded-full text-white border border-white-500 flex justify-center items-center">CA</div>
                <div class="bg-blue-600 text-sm w-8 h-8 font-semibold rounded-full text-white border border-white-500 flex justify-center items-center">JS</div>
                <div class="bg-blue-600 text-sm w-8 h-8 font-semibold rounded-full text-white border border-white-500 flex justify-center items-center">B</div>
            </div>
            <div class="text-sm text-gray-500">9 months ago</div>
        </div>
  </div>
        </div>
  </div>

  {% endblock tasks %}
  

users/templates/signin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
     <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <header class="py-3 bg-red-400">
        <div class="nav-bar flex justify-around">
            <div class="logo">Event</div>
            <div class="menu">
                <ul class="flex justify-between gap-4 text-white">
                    <li><a href="#">Home</a></li>
                    <li><a href="{% url 'signin' %}">Log In</a></li>
                    
                </ul>
            </div>
        </div>
    </header>
     <form action="{% url 'signin' %}" method="post" class="form">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Log In</button>
         <p style="color: #727171;">If you don't have account please <a href="{% url 'sign-up' %}" style="color: green; text-decoration: underline;">Register</a></p>
    </form>
   
</body>
</html>

users/templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Document</title>
</head>
<body>
    <header class="py-3 bg-red-400">
        <div class="nav-bar flex justify-around">
            <div class="logo">Event</div>
            <div class="menu">
                <ul class="flex justify-between gap-4 text-white">
                    <li><a href="#">Home</a></li>
                    <li><a href="{% url 'signin' %}">Log In</a></li>
                    
                </ul>
            </div>
        </div>
    </header>
    {% if messages %}
        {% for message in messages  %}
            {{message}}
        {% endfor %}
    {% endif %}
<form action="{% url 'sign-up' %}" method="post" class="form">

    {% csrf_token %}
    {% if form.non_field_errors %}
            {% for error in form.non_field_errors  %}
                {{error}}
            {% endfor %}
        {% endif %}
    {% for field in form  %}
      <p>
        <label for="{{field.id_for_label}}">{{field.label}}</label>
        {{field}}
        
        {% if field.errors %}
            {% for error in field.errors  %}
                {{error}}
            {% endfor %}
        {% endif %}
      </p>
    {% endfor %}
    <button type="submit">Submit</button>
    <p style="color: gray;">If you already registered please <a href="{% url 'signin' %}" style="color: green; text-decoration: underline;">Sign In</a></p>
</form>

</body>
</html>